name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Set version and branch environment variables
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION="${{ github.ref }}"
            VERSION=${VERSION#refs/tags/} # Strip 'refs/tags/' prefix
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            VERSION="${{ github.ref }}"
            VERSION=${BRANCH_NAME#refs/heads/} # Strip 'refs/heads/' prefix
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=v(.*),group=1,value=${{ github.ref_name }},enable=${{ github.event_name == 'release' }}
            type=ref,event=branch
          flavor: |
            latest=false

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}
            BRANCH_NAME=${{ env.BRANCH_NAME }}
